import { GitHubService } from './github';
import { AssessmentFinding } from '@/types/assessments/models';

export class RemediationEngine {
  private gitHub = new GitHubService();

  async proposeFix(finding: AssessmentFinding, resourceName: string): Promise<{ success: boolean; prUrl?: string }> {
    console.log(`[Remediation] Generating fix for ${finding.id}...`);

    const fix = this.generateTerraformFix(finding, resourceName);
    if (!fix) return { success: false };

    try {
      const branch = `fix/${finding.id}-${resourceName.replace(/ /g, '-')}`;
      await this.gitHub.createBranch(branch);
      await this.gitHub.commitFile(branch, `infrastructure/terraform/${resourceName}.tf`, fix, `fix: remediate ${finding.title}`);
      
      const pr = await this.gitHub.openPullRequest(
        `Remediation: ${finding.title}`,
        `This PR was automatically generated by NarangOS to fix a ${finding.severity} risk.\n\n**Finding:** ${finding.title}\n**Evidence:** ${finding.evidence}`,
        branch
      );

      return { success: true, prUrl: pr.prUrl };
    } catch (e) {
      console.error('Remediation failed:', e);
      return { success: false };
    }
  }

  private generateTerraformFix(finding: AssessmentFinding, resourceName: string): string | null {
    switch (finding.id) {
      case 'K8S-AVAIL-001':
        return `resource "kubernetes_pod_disruption_budget" "${resourceName}_pdb" {
  metadata {
    name = "${resourceName}-pdb"
  }
  spec {
    minAvailable = 1
  }
}`;
      case 'K8S-AVAIL-002':
        return `# Manual intervention required for Topology Spread Constraints\n# Please implement topologySpreadConstraints for ${resourceName}`;
      default:
        return null;
    }
  }
}
